CREATE TABLE authors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    bio  VARCHAR(2000),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

CREATE TABLE books
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    isbn           VARCHAR(255)                            NOT NULL,
    published_date date                                    NOT NULL,
    author_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE borrows
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    borrow_date date                                    NOT NULL,
    return_date date,
    user_id     BIGINT                                  NOT NULL,
    book_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_borrows PRIMARY KEY (id)
);

CREATE TABLE profiles
(
    id        BIGINT       NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    phone     VARCHAR(255),
    address   VARCHAR(255),
    CONSTRAINT "pk_profiles" PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE books
    ADD CONSTRAINT uc_62e5f1e7f8ebda483190bd35d UNIQUE (isbn);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);

ALTER TABLE authors
    ADD CONSTRAINT uc_de8b9c8ca7beb14e87063f5ee UNIQUE (name);

ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);

ALTER TABLE borrows
    ADD CONSTRAINT FK_BORROWS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

CREATE INDEX idx_borrow_book ON borrows (book_id);

ALTER TABLE borrows
    ADD CONSTRAINT FK_BORROWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_borrow_user ON borrows (user_id);

ALTER TABLE profiles
    ADD CONSTRAINT FK_PROFILES_ON_ID FOREIGN KEY (id) REFERENCES users (id);